<?php

$permisions =[
    'stores.index',
    'stores.create',
    'stores.edit',
    'stores.delete',
    'roles.index',
    'roles.create',
    'roles.edit',
    'roles.delete',
    'permissions.index',
    'permissions.create',
    'permissions.edit',
    'permissions.delete',
    'roles.permissions',
    'guarantees.index',
    'guarantees.create',
    'guarantees.edit',
    'guarantees.delete',
    'guarantees.warehouse.index',
    'guarantees.warehouse.create',
    'guarantees.warehouse.edit',
    'guarantees.warehouse.delete',
    'customers.index',
    'customers.create',
    'customers.edit',
];
